apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspi-benchmark
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python
        ports:
        - containerPort: 80