apiVersion: v1
kind: Service
metadata:
  name: flask-deploy-test
spec:
  selector:
    app: flask-deploy-test
  ports:
    - protocol: "TCP"
     port: 6000
     targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: flask-deploy-test
spec:
  selector:
    matchLabels:
      app: flask-deploy-test
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-deploy-test
    spec:
      containers:
      - name: flask-deploy-test
        image: docker.io/horri1520/flask-deploy-test
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000